export const ActionTypes = {

    REGISTER_REQUEST : "REGISTER_REQUEST",
    REGISTER_REQUEST_SUCCESS : "REGISTER_REQUEST_SUCCESS",
    REGISTER_REQUEST_FAILED : "REGISTER_REQUEST_FAILED",

    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_REQUEST_SUCCESS : "LOGIN_REQUEST_SUCCESS",
    LOGIN_REQUEST_FAILED : "LOGIN_REQUEST_FAILED",

    LOGOUT_REQUEST : "LOGOUT_REQUEST",


    HOME_REQUEST : "HOME_REQUEST",
    HOME_REQUEST_SUCCESS : "HOME_REQUEST_SUCCESS",
    HOME_REQUEST_FAILED : "HOME_REQUEST_FAILED",

    GET_PROFILE_REQUEST : "GET_PROFILE_REQUEST",
    GET_PROFILE_REQUEST_SUCCESS : 'GET_PROFILE_REQUEST_SUCCESS',
    GET_PROFILE_REQUEST_FAILED : "GET_PROFILE_REQUEST_FAILED",

    

    
    
}